name: dift_diftnerf
channels:
  - xformers
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python==3.9
  - pip==23.0.1 
  - pip:
      - accelerate==0.19.0
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - anyio==3.7.0
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.2.3
      - asttokens==2.2.1
      - async-lru==2.0.2
      - async-timeout==4.0.2
      - attrs==23.1.0
      - babel==2.12.1
      - backcall==0.2.0
      - beautifulsoup4==4.12.2
      - bleach==6.0.0
      - brotli==1.0.9
      - cmake==3.26.3
      - comm==0.1.3
      - contourpy==1.0.7
      - cycler==0.11.0
      - debugpy==1.6.7
      - decorator==5.1.1
      - defusedxml==0.7.1
      - diffusers==0.15.0
      - exceptiongroup==1.1.1
      - executing==1.2.0
      - fastjsonschema==2.17.1
      - filelock==3.12.0
      - fonttools==4.39.4
      - fqdn==1.5.1
      - frozenlist==1.3.3
      - fsspec==2023.5.0
      - gevent==22.10.2
      - geventhttpclient==2.0.2
      - greenlet==2.0.2
      - grpcio==1.54.2
      - huggingface-hub==0.14.1
      - importlib-metadata==6.6.0
      - ipykernel==6.23.1
      - ipympl==0.9.3
      - ipython==8.13.2
      - ipython-genutils==0.2.0
      - ipywidgets==8.0.6
      - isoduration==20.11.0
      - jedi==0.18.2
      - jinja2==3.1.2
      - json5==0.9.14
      - jsonpointer==2.3
      - jsonschema==4.17.3
      - jupyter-client==8.2.0
